class_name StatesRef

#BALL
const BALL_IDLE = 'BALL_IDLE'
const BALL_MOVING = 'BALL_MOVING'

#CUE
const CUE_CHARGING = 'CUE_CHARGING'
const CUE_IDLE = 'CUE_IDLE'
const CUE_SPINNING = 'CUE_SPINNING'
const CUE_JUMPING = 'CUE_JUMPING'
const CUE_LOCKED = 'CUE_LOCKED'
const CUE_RECOVER = 'CUE_RECOVER'

#TABLE
const GAME_STARTING = 'GAME_STARTING'
const GAME_FINISHED = 'GAME_FINISHED'
const GAME_STARTED = 'GAME_STARTED'
const GAME_WAITING_START = 'GAME_WAITING_START'

#PLAYER
const PLAYER_IDLE = 'PLAYER_IDLE'
const PLAYER_WALKING = 'PLAYER_WALKING'
