class_name PoolTurnCommands extends RefCounted

const CALL_NEXT_TURN = 'NEXT_TURN'
const CALL_EXTEND_TURN = 'EXTEND_TURN'
const CALL_MATCH_OVER_WINNER = 'MATCH_IS_OVER_WINNER'
const CALL_MATCH_OVER_LOSER = 'MATCH_IS_OVER_LOSER'
const CALL_BALL_REPLACEMENT = 'BALL_REPLACEMENT'
